### ISSUE TITLE
Proficiencies TODO

### ISSUE THREAD

**Issue by oestrich** [oestrich/ex_venture#110]
Missing from proficiencies still:

- [ ] train new proficiencies from npc trainers
- [x] hone your proficiencies
- [ ] display what you do have for a missing requirement when moving.
- [ ] when looking in a direction, show if you meet the requirement or not
  - [ ] if not display what you have
