### ISSUE TITLE
Overworld TODO

### ISSUE THREAD

**Issue by oestrich** [oestrich/ex_venture#63]
Known issues with the overworld

- [ ] Change the map size
  - [ ] Sector processes are started/stopped depending on new size
- [ ] background map colors
- [ ] On login, the game checks if your room is still available, this should work with the overworld
- [ ] Items in the overworld
- [ ] Item pick up
- [ ] Dropping an item
- [ ] Listening on the overworld
- [ ] Shops, maybe
- [ ] Look in a direction
- [ ] Say/emote/whisper might want to echo further than the exact same cell
- [ ] Doors
- [x] Creating exits into/out of the overworld
- [x] Scanning
- [x] "Empty" cells should not get exits to
